### ISSUE TITLE
Need help with setup

### ISSUE THREAD

**Issue by hem0773** [sp9wpn/freq_cycler#1]
Hi !
I only use a USB SDR and dxlAPPS for probe reception and only want to scan known frequencies, then I have to enter them in the config.cfg or like my example

Do I have to specify "-no-blind" then?

; known sondes frequencies, space-delimited
Known=402100 403000 401100 405100

and what does the parameter do

; cycle length (sec)
CycleInterval=19

**Comment by sp9wpn** [comment]
Yes: -no-blind and listing few frequencies as you did is the right choice for you.

CycleInterval is the basic time between each cycle (change of frequency set).
